### PR TITLE
Making macOS web view controller public

### PR DESCRIPTION
**Pull request by vojto**
I'm trying to use web view controller from custom subclass of AuthorizerUI. So I need these things public:

- initializer
- `interceptURLString`
- `onIntercept`
- `onWillCancel`

Feel free to close if the use case doesn't make sense. I'm doing too much customisation.

Overall goal is to show the view controller in my own window which is part of wizard-like dialog.

### CODE REVIEW

**Comment by p2** [comment]
Happy to pull this in, just want to make sure I understand the need. The initializer I understand, can you explain briefly why you need the other three parts open/public?

**Comment by vojto** [comment]
I'm implementing my own class conforming to `OAuth2AuthorizerUI`. It lets other parts of my code take care of showing/hiding the view controller into appropriate place of app UI.

Body of `presentableAuthorizeViewController` is just copied from your implementation, and that's the code that uses those private variables.

I want the Authorizer UI, sans window/sheet stuff. 

```swift
class CustomAuthorizer: OAuth2AuthorizerUI {
    
    public unowned let oauth2: OAuth2Base
    
    public var presentViewController: ((OAuth2WebViewController) -> ())?
    public var dismissViewController: ((OAuth2WebViewController) -> ())?
    
    var viewController: OAuth2WebViewController?
    
    public init(oauth2: OAuth2Base) {
        self.oauth2 = oauth2
    }
    
    public func openAuthorizeURLInBrowser(_ url: URL) throws {
        fatalError("not implemented")
    }
    
    public func authorizeEmbedded(with config: OAuth2AuthConfig, at url: URL) throws {

        viewController = try presentableAuthorizeViewController(at: url)
        presentViewController?(viewController!)
        
        oauth2.internalAfterAuthorizeOrFail = { wasFailure, error in
            self.dismissViewController?(self.viewController!)
            self.viewController = nil
        }
    }
    
    func presentableAuthorizeViewController(at url: URL) throws -> OAuth2WebViewController {
        let controller = OAuth2WebViewController()
        controller.startURL = url
        controller.interceptURLString = oauth2.redirect!
        controller.onIntercept = { url in
            do {
                try self.oauth2.handleRedirectURL(url)
                return true
            }
            catch let error {
                self.oauth2.logger?.warn("OAuth2", msg: "Cannot intercept redirect URL: \(error)")
            }
            return false
        }
        controller.onWillCancel = {
            self.oauth2.didFail(with: nil)
        }
        
        reset()
        
        
        return controller
    }
    
    func reset() {
        let types = Set([WKWebsiteDataTypeCookies, WKWebsiteDataTypeSessionStorage, WKWebsiteDataTypeDiskCache, WKWebsiteDataTypeMemoryCache])
        let from = Date(timeIntervalSince1970: 0)
        WKWebsiteDataStore.default().removeData(ofTypes: types, modifiedSince: from) { }
        
        /*
        NSHTTPCookieStorage *storage = [NSHTTPCookieStorage sharedHTTPCookieStorage];
        for (NSHTTPCookie *cookie in [storage cookies])
        {
            [storage deleteCookie:cookie];
        }
         */
        
        let storage = HTTPCookieStorage.shared
        for cookie in storage.cookies ?? [] {
            storage.deleteCookie(cookie)
        }
    }
}
```

**Comment by p2** [comment]
Ah of course, those must be public so you can actually use `OAuth2WebViewController`. Just curious, why is `webView` also public?

**Comment by vojto** [comment]
@p2 Whooops, didn't mean to push that out. It doesn't need to be.

Thanks!

**Pull request merged**
