### PR TITLE
accessMode not configurable for tokens stored in keychain issue #92

### PR DESCRIPTION
**Pull request by tompson**

### CODE REVIEW

**Comment by p2** [comment]
This shouldn't be an ivar on OAuth2Base, it should be a property of `OAuth2AuthConfig`, used in `OAuth2.authConfig`, initialized from settings dictionary in `OAuth2.init(settings:)`.

(And please use tabs ;) )

**Comment by tompson** [comment]
ok, I thought because `useKeychain` is a property of `OAuth2Base` this would be correct, will change it

**Comment by p2** [comment]
Hmm, that is a good point. `useKeychain` needs to be on the base class because it can store other things, maybe you're right and this setting should be on base as well.

**Comment by p2** [comment]
Ok yes, you're right, leave it there. But please use spaces and make the dictionary key underscore to be consistent. 👍🏼

**Comment by tompson** [comment]
ok, I fixed the indention

what do you mean by "make the dictionary key underscore to be consistent" - I do not see any dictionary keys with underscores

**Comment by p2** [comment]
They are in the `OAuth2` class: https://github.com/p2/OAuth2/blob/master/Sources/Base/OAuth2.swift#L130

**Comment by p2** [comment]
Oh, I did not get a notification that you fixed this, sorry. There is PR #70 waiting that updates `SwiftKeychain` to the latest version, which changes how this would work. Let me merge that one and do some refactoring, then we can see whether you want to update this PR or whether I can quickly implement what you propose here.

**Comment by p2** [comment]
I've just pushed an adaptation of your implementation to `develop`, can you check @tompson and let me know if it works for you?

**Comment by tompson** [comment]
tested it with `develop` branch, looks good to me, works with my application

**Comment by p2** [comment]
Alright great, I'll publish this as 2.2.2, thanks!

**Pull request closed without merging**
