### PR TITLE
Release 4.0.1 on CocoaPods

### PR DESCRIPTION
**Pull request by djbe**
We have 2 choices here:
- Set the spec version to 4.0.0, move the github tag to this commit (once merged), and then push the spec.
- Set the spec version to 4.0.1, release this new version on github and push the spec.

I'd recommend the 2nd option, as there have been some changes/fixes to master since 4.0.0 was released.

### CODE REVIEW

**Comment by djbe** [comment]
We should also discuss how you'd like to push the spec. Either:
- You push the spec (run `pod trunk push`)
- I push the spec, but then you'll need to add me as an author on cocoapods ([link](https://guides.cocoapods.org/terminal/commands.html#pod_trunk_add_owner)). You can always remove me afterwards 😄

**Comment by p2** [comment]
I've tagged current master with 4.0.1, I like your second idea (in both posts). DM me your email address @phaseofmatter on Twitter and I'll make you an owner. Thanks!

**Comment by djbe** [comment]
This PR will still need to be merged, and the 4.0.1 tag moved, for cocoapods spec linting to work.

I can't seem to DM you on twitter until we follow each other, I think?

**Comment by p2** [comment]
I thought it's now possible to DM anybody? Did you try, otherwise @-me so I know your handle.

**Comment by djbe** [comment]
Tried it both in the mac app and on their website:
screen shot 2017-11-07 at 18 48 53

Anyway, I sent you a public message.

**Comment by p2** [comment]
Added!

**Comment by djbe** [comment]
It's been pushed! 🎉

**Pull request merged**
