### PR TITLE
Add password grant and tests 

### PR DESCRIPTION
**Pull request by trsneed**
Added a password grant type as well as a few tests to check for certain conditions.

### CODE REVIEW

**Comment by trsneed** [comment]
I meant to do this in a separate branch, but completely forgot. I hope that is not too annoying.

**Comment by p2** [comment]
No worries, looks great, thanks a lot!

(I should add a contributors file...)

**Comment by trsneed** [comment]
Thank you so much!

**Comment by p2** [comment]
I'll try to get a new version out soon and up on CocoaPods, currently a bit underwater so it'll be a few days I'm afraid.

**Comment by trsneed** [comment]
That's fine. I am tied to HEAD right now to use the features. I'll pay attention though for when it is released.

**Pull request merged**
