### PR TITLE
fixed issue with wrong state-machine after pull down gesture on presented SFSafariViewController

### PR DESCRIPTION
**Pull request by cbruns1985**
In case the SFSafariViewController is presented modally, it can be dismissed via pull down gesture. In that case the state machine is completely broken. Therefore I added the presentationDelegate, which ensures that the same logic is triggered as in case the "Finished" button is pressed with this interaction.

### CODE REVIEW

**Comment by ossus-lib** [comment]
I missed this, @cbruns1985 would you mind re-targeting this request to `main` so I can merge it?

**Comment by cbruns1985** [comment]
@ossus-lib pretty difficult, due to my fork does not have the branches. Let me check how I can somehow make this happen ...

**Comment by cbruns1985** [comment]
https://github.com/p2/OAuth2/pull/414 had to remove the branch and reopen another one with the correct bases from main. Find here a new PR.

**Comment by cbruns1985** [comment]
Had to create a new branch.

**Pull request closed without merging**
