### PR TITLE
Update returning error to ignore noRefreshToken

### PR DESCRIPTION
**Pull request by dhardiman**
Fix for issue discussed on #232 

@KimKellerRasmussen does this fix your issue?

### CODE REVIEW

**Comment by KimKellerRasmussen** [comment]
@dhardiman yes, it seems to fix the issue... However, I haven't done a thorough test.

**Comment by dhardiman** [comment]
👍

**Comment by p2** [comment]
I'm currently out and can't test, but I think this also breaks dynamic client registration (looking at lines 109-121). Can you make the same exception for `OAuth2Error.noClientId`? Then everything should work again; at a later stage the whole flow can be cleaned up a bit.

**Comment by dhardiman** [comment]
Updated...

**Comment by p2** [comment]
Thank you!!

**Pull request merged**
