### PR TITLE
Option to put access_token into uri instead of header

### PR DESCRIPTION
**Pull request by pascalfribi**
- Changed minimal target to 10.10
- Updated XCode setting  to recommended warnings
- Added option to put access_token into uri instead of header. This is needed for some Websites.
This can be configured by putting request_access_token_placement into the settings json with value of "header" (default) or "uri" or set the oauth2.clientConfig.requestAccessTokenPlacement to header or uri.

### CODE REVIEW

**Comment by p2** [comment]
I'm unable to support this framework at this time. And for this PR, this shouldn't be an option since it's non-standard behavior, this should be a subclass, like all the other special-behaviors.

**Comment by pascalfribi** [comment]
Hi Pascal,

good to know. I will keep my private repo then. Maybe you should add an indication in the Readme that you do not support the Framework anymore (which is a pitty).

Concerning my pull request: this is not at all a non standard behaviour. Look at https://tools.ietf.org/html/rfc6750#section-2 <https://tools.ietf.org/html/rfc6750#section-2> . Here you will see three possible methods where the token can be put in. And I just implemented one of these possibilities so that the code can be used with other sites as well. But it is your code and your decision!

I wish you a happy christmas!

Regards

Pascal

**Comment by p2** [comment]
Yeah I should indicate that; still hoping a friend can take over.

To clarify, it’s a _non-suggested_ flow since it’s not secure. I want to make it hard to use the library in non-secure ways, an option is too easy. :)

**Comment by pascalfribi** [comment]
Well as a client you do not really have a choice if the backend does not allow anything else. But it is your decision.

**Pull request closed without merging**
