### PR TITLE
add dependency to e2LoggerProtocol, update to allow for more detailed logging

### PR DESCRIPTION
**Pull request by ChrisInIssaquah**
Allow user to supply a more flexible logger interface.  Provide for more detailed OAuth2 log messages when set to .trace level.

### CODE REVIEW

**Comment by p2** [comment]
Have you seen discussion in #82 ? Is it possible to do this without the added dependency?

**Comment by ChrisInIssaquah** [comment]
You should look at the project.  It is just two files, one of which is a protocol.  The only other option is just to stick these two files into OAuth2, but I also use this interface in other places.  I made the dependency as small as possible, certainly much smaller than Cocoa Lumberjack.

**Comment by ChrisInIssaquah** [comment]
You should look at the project.  It is just two files, one of which is a protocol.  The only other option is just to stick these two files into OAuth2, but I also use this interface in other places.  I made the dependency as small as possible, certainly much smaller than Cocoa Lumberjack.

The idea is to use a very simple protocol definition, and then let people implement as simple or complex an implementation as they choose.

In order to not break things I provide a very simple implementation, but normally a larger app would inject its own logger that conformed to the protocol.

**Comment by p2** [comment]
It seems rather complicated the way it's set up right now. This could be replicated with a very simple built-in logging protocol and a base logger provided by OAuth2 that you could then adapt to your liking (and your protocol). Would that work for you?

**Comment by ChrisInIssaquah** [comment]
That is fine.  But I need to be able to inject my implementation of the logger at a class level, rather than having to instance within each OAuth2 instance.  This is mainly for use with Swift-SMART, which has the OAuth2 implementations buried.  I also added a much more detailed logging of the NSURLResponse and NSURLRequest in OAuthBase.swift.

What I have provided you is exactly what you describe, just a simple protocol and a simple implementation.  While you can stick those into OAuth2, it is really kind of tangential to what OAuth2 is doing.  A better option would be to take an create a p2Logger as a separate project that can then be used by the various projects using OAuth2 and Swift-SMART.

The problem2 with the current OAuth2
1) It does not allow a full trace of the network exchange, just messages about when things occurs
2) Even passing in verbose=true from Swift-SMART looks pretty complicated, because it has to be done at the OAuth2 instance level, rather than the class level.

**Comment by p2** [comment]
I see, but then it makes more sense to change this on the SMART framework where it can be an ivar instead of static class properties. The `verbose` flag is [passed through to OAuth2](https://github.com/smart-on-fhir/Swift-SMART/blob/master/Sources/Client/Client.swift#L89), you can just specify it on the SMART settings dict. You could also substitute your own `FHIRServer` class with the Client's `init(server:)` method.

Do you need this for auth debugging of the server or of the client? The OAuth2 client performs the standard OAuth2 exchange, the only variable parts are extra parameters passed in and what's returned when the token comes back, which is logged to stdout.

**Comment by ChrisInIssaquah** [comment]
Introducing too much complexity into target projects

**Comment by p2** [comment]
@ChrisInIssaquah , on latest `develop` I have now implemented a simple protocol. Still works for debug logging via the `verbose` setting, for full tracing (which now dumps full request/response pairs you can do:

```swift
oauth2.logger = OAuth2DebugLogger(.Trace)
```

I'll merge into master soon and expose on the SMART framework accordingly.

**Comment by ChrisInIssaquah** [comment]
Looking forward to it.  I have an interim solution I am working with, but much better to have you integrate into the core product set.

**Comment by p2** [comment]
Added to Swift-SMART: `client.server.logger` (automatically set when _verbose_, sets the same logger on OAuth2).

**Pull request closed without merging**
