### PR TITLE
Improved refresh token support

### LINKED ISSUE #47: OAuth2PasswordGrant should parse refresh token
Hi,

I'm using `OAuth2PasswordGrant` in my project and I don't think the "password" flow is fully implemented.

First, `OAuth2PasswordGrant` will try to use the `authorization_uri` instead of the `token_uri` to request and `access_token` using the `username` and `password`. (This can be hacked by using the a token uri as the `authorization_uri` value).

Second, I believe all grant types allow to refresh `access_token` using the `refresh_token`. I just see this implemented in `OAuth2CodeGrant`. I think all the refresh logic (`refreshToken`, `doRefreshToken()`, ...) should be shared with `OAuth2PasswordGrant`.

Cheers.

### PR DESCRIPTION
**Pull request by glennschmidt**
Fixes #47

Move refresh token logic from the OAuth2CodeGrant class to the base OAuth2 class, so that it applies whenever the server returns a refresh token (for any grant type).

Support the tokenURL parameter for all grant types, and use it when requesting a JSON response. If it's nil, fall back to using the authURL instead.

Fix up some comments.

### CODE REVIEW

**Comment by p2** [comment]
Can you fix indenting? Seems your Xcode is using spaces instead of tabs.

**Comment by glennschmidt** [comment]
Sorry about that. I really wish Xcode would adapt to the indentation style of the file being edited.

**Comment by p2** [comment]
Same here, usually only catch in in PR review. :P Sublime does it perfectly...

**Comment by glennschmidt** [comment]
Fixed

**Comment by p2** [comment]
Alright great, thanks! I'll merge with the intent to refactoring some parts (like creating classes for the auth/token requests). But don't quote me on it! :)

**Pull request merged**
