### PR TITLE
Exclude OSAuth2Tests in release builds to fix #85

### LINKED ISSUE #85: Carthage support
Hey, do you plan on supporting Carghage? It would really help :) Currently all I get is a bunch of errors about failed tests.

### PR DESCRIPTION
**Pull request by davidpeckham**
This allows Carthage to build OAuth2 for Mac

### CODE REVIEW

**Comment by p2** [comment]
Interesting. Building tests is OFF for archive builds and I don't see where this inclusion is configured in Xcode. Thanks, I'll pull this in and see what happens.

**Comment by davidpeckham** [comment]
Thanks for pulling this in. This setting is in the scheme editor:

oauth2-mac-scheme

**Comment by p2** [comment]
Hmm, interesting that Carthage chokes on this. Well I guess I can settle on using <key>CMD</key> + <key>U</key>.

**Comment by davidpeckham** [comment]
Carthage calls `xcodebuild`, which builds for Release by default:

```
$ cd ~Code/GitHub/OAuth2
$ xcodebuild
=== BUILD TARGET OAuth2OSX OF PROJECT OAuth2 WITH THE DEFAULT CONFIGURATION (Release) ===
```

New framework projects exclude unit tests for the Run scheme, at least in the latest Xcode. Did OAuth2 start off as an application project?

You can see the same errors in Xcode -- just include OAuth2Tests in the Archive build:

oauth2-scheme

and then choose Product > Archive:

archive-build-errors

**Comment by p2** [comment]
IIRC I have manually enabled unit tests for the run phase early on for testing. I was just confused why Carthage would use the Run phase instead of the Archive phase since I don't know Carthage, but makes sense if it integrates with Xcode and doesn't just build a linkable framework.

**Comment by davidpeckham** [comment]
Good point. Apparently, Carthage authors found that `xcodebuild archive` doesn't work for the simulator SDK:

https://github.com/Carthage/Carthage/issues/169

**Pull request merged**
